### ISSUE TITLE
Weird issue when running rake spec

### ISSUE THREAD

**Issue by bechampion** [jtopjian/puppet-reprepro#60]
Hi there , I'm following your tutorial and when I run rake spec i get this:
/home/dsa/.rvm/gems/ruby-2.3.0/gems/puppet-3.6.2/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
        from /home/jegarcia/.rvm/gems/ruby-2.3.0/gems/puppet-3.6.2/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
        from /home/jegarcia/.rvm/gems/ruby-2.3.0/gems/puppet-3.6.2/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'

I'm using puppet 4.5.2 and ruby 2.3.0 ... any clues?  I've cloned your repo did bundle install and rake spec.

Thanks a lot!

**Comment by bechampion** [comment]
fixed it with:
https://github.com/dtao/safe_yaml/commit/26c235da7ad0529fe3aaa5a023503138cf8cf7c9
in case someone needs it.
